In [31]:
%matplotlib inline
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.datasets import load_wine

from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

* We have loaded the necessary libraries above
* Now let's load the data

In [59]:
data = load_wine(as_frame=True)
df = data.data.copy()  # features
# Look at the documentation (https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_wine.html)
# and save the label in a column called 'y' in df.
df['y'] = data['frame']['target'] ## YOUR CODE HERE # label
df.tail()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,y
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560.0,2

In [60]:
data['DESCR'].split('\n')

['.. _wine_dataset:',
 '',
 'Wine recognition dataset',
 '------------------------',
 '',
 '**Data Set Characteristics:**',
 '',
 '    :Number of Instances: 178 (50 in each of three classes)',
 '    :Number of Attributes: 13 numeric, predictive attributes and the class',
 '    :Attribute Information:',
 ' \t\t- Alcohol',
 ' \t\t- Malic acid',
 ' \t\t- Ash',
 '\t\t- Alcalinity of ash  ',
 ' \t\t- Magnesium',
 '\t\t- Total phenols',
 ' \t\t- Flavanoids',
 ' \t\t- Nonflavanoid phenols',
 ' \t\t- Proanthocyanins',
 '\t\t- Color intensity',
 ' \t\t- Hue',
 ' \t\t- OD280/OD315 of diluted wines',
 ' \t\t- Proline',
 '',
 '    - class:',
 '            - class_0',
 '            - class_1',
 '            - class_2',
 '\t\t',
 '    :Summary Statistics:',
 '    ',
 '    ============================= ==== ===== ======= =====',
 '                                   Min   Max   Mean     SD',
 '    ============================= ==== ===== ======= =====',
 '    Alcohol:                      11.0  14.8    13.0   0.8',
 '    Malic Acid:                   0.74  5.80    2.34  1.12',
 '    Ash:                          1.36  3.23    2.36  0.27',
 '    Alcalinity of Ash:            10.6  30.0    19.5   3.3',
 '    Magnesium:                    70.0 162.0    99.7  14.3',
 '    Total Phenols:                0.98  3.88    2.29  0.63',
 '    Flavanoids:                   0.34  5.08    2.03  1.00',
 '    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12',
 '    Proanthocyanins:              0.41  3.58    1.59  0.57',
 '    Colour Intensity:              1.3  13.0     5.1   2.3',
 '    Hue:                          0.48  1.71    0.96  0.23',
 '    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71',
 '    Proline:                       278  1680     746   315',
 '    ============================= ==== ===== ======= =====',
 '',
 '    :Missing Attribute Values: None',
 '    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)',
 '    :Creator: R.A. Fisher',
 '    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)',
 '    :Date: July, 1988',
 '',
 'This is a copy of UCI ML Wine recognition datasets.',
 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',
 '',
 'The data is the results of a chemical analysis of wines grown in the same',
 'region in Italy by three different cultivators. There are thirteen different',
 'measurements taken for different constituents found in the three types of',
 'wine.',
 '',
 'Original Owners: ',
 '',
 'Forina, M. et al, PARVUS - ',
 'An Extendible Package for Data Exploration, Classification and Correlation. ',
 'Institute of Pharmaceutical and Food Analysis and Technologies,',
 'Via Brigata Salerno, 16147 Genoa, Italy.',
 '',
 'Citation:',
 '',
 'Lichman, M. (2013). UCI Machine Learning Repository',
 '[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,',
 'School of Information and Computer Science. ',
 '',
 '.. topic:: References',
 '',
 '  (1) S. Aeberhard, D. Coomans and O. de Vel, ',
 '  Comparison of Classifiers in High Dimensional Settings, ',
 '  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of  ',
 '  Mathematics and Statistics, James Cook University of North Queensland. ',
 '  (Also submitted to Technometrics). ',
 '',
 '  The data was used with many others for comparing various ',
 '  classifiers. The classes are separable, though only RDA ',
 '  has achieved 100% correct classification. ',
 '  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data)) ',
 '  (All results using the leave-one-out technique) ',
 '',
 '  (2) S. Aeberhard, D. Coomans and O. de Vel, ',
 '  "THE CLASSIFICATION PERFORMANCE OF RDA" ',
 '  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of ',
 '  Mathematics and Statistics, James Cook University of North Queensland. ',
 '  (Also submitted to Journal of Chemometrics).',
 '']

In [73]:
data

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:                          1.36  3.23    2.36  0.27\n    Alcalinity of Ash:            10.6  30.0    19.5   3.3\n    Magnesium:                    70.0 162.0    99.7  14.3\n    Total Phenols:                0.98  3.88    2.29  0.63\n    Flavanoids:                   0.34  5.08    2.03  1.00\n    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12\n    Proanthocyanins:              0.41  3.58    1.59  0.57\n    Colour Intensity:              1.3  13.0     5.1   2.3\n    Hue:                          0.48  1.71    0.96  0.23\n    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71\n    Proline:                       278  1680     746   315\n    ============================= ==== ===== ======= =====\n\n    :Missing Attribute Values: None\n    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThis is a copy of UCI ML Wine recognition datasets.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data\n\nThe data is the results of a chemical analysis of wines grown in the same\nregion in Italy by three different cultivators. There are thirteen different\nmeasurements taken for different constituents found in the three types of\nwine.\n\nOriginal Owners: \n\nForina, M. et al, PARVUS - \nAn Extendible Package for Data Exploration, Classification and Correlation. \nInstitute of Pharmaceutical and Food Analysis and Technologies,\nVia Brigata Salerno, 16147 Genoa, Italy.\n\nCitation:\n\nLichman, M. (2013). UCI Machine Learning Repository\n[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,\nSchool of Information and Computer Science. \n\n.. topic:: References\n\n  (1) S. Aeberhard, D. Coomans and O. de Vel, \n  Comparison of Classifiers in High Dimensional Settings, \n  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of  \n  Mathematics and Statistics, James Cook University of North Queensland. \n  (Also submitted to Technometrics). \n\n  The data was used with many others for comparing various \n  classifiers. The classes are separable, though only RDA \n  has achieved 100% correct classification. \n  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data)) \n  (All results using the leave-one-out technique) \n\n  (2) S. Aeberhard, D. Coomans and O. de Vel, \n  "THE CLASSIFICATION PERFORMANCE OF RDA" \n  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of \n  Mathematics and Statistics, James Cook University of North Queensland. \n  (Also submitted to Journal of Chemometrics).\n',
 'data':      alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
 0      14.23        1.71  2.43               15.6      127.0           2.80
 1      13.20        1.78  2.14               11.2      100.0           2.65
 2      13.16        2.36  2.67               18.6      101.0           2.80
 3      14.37        1.95  2.50               16.8      113.0           3.85
 4      13.24        2.59  2.87               21.0      118.0           2.80
 ..       ...         ...   ...                ...        ...            ...
 173    13.71        5.65  2.45               20.5       95.0           1.68
 174    13.40        3.91  2.48               23.0      102.0           1.80
 175    13.27        4.28  2.26               20.0      120.0           1.59
 176    13.17        2.59  2.37               20.0      120.0           1.65
 177    14.13        4.10  2.74               24.5       96.0           2.05

      flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
 0          3.06                  0.28             2.29             5.64  1.04
 1          2.76                  0.26             1.28             4.38  1.05
 2          3.24                  0.30             2.81             5.68  1.03
 3          3.49                  0.24             2.18             7.80  0.86
 4          2.69                  0.39             1.82             4.32  1.04
 ..          ...                   ...              ...              ...   ...
 173        0.61                  0.52             1.06             7.70  0.64
 174        0.75                  0.43             1.41             7.30  0.70
 175        0.69                  0.43             1.35            10.20  0.59
 176        0.68                  0.53             1.46             9.30  0.60
 177        0.76                  0.56             1.35             9.20  0.61

      od280/od315_of_diluted_wines  proline
 0                            3.92   1065.0
 1                            3.40   1050.0
 2                            3.17   1185.0
 3                            3.45   1480.0
 4                            2.93    735.0
 ..                            ...      ...
 173                          1.74    740.0
 174                          1.56    750.0
 175                          1.56    835.0
 176                          1.62    840.0
 177                          1.60    560.0

 [178 rows x 13 columns],
 'feature_names': ['alcohol',
  'malic_acid',
  'ash',
  'alcalinity_of_ash',
  'magnesium',
  'total_phenols',
  'flavanoids',
  'nonflavanoid_phenols',
  'proanthocyanins',
  'color_intensity',
  'hue',
  'od280/od315_of_diluted_wines',
  'proline'],
 'frame':      alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
 0      14.23        1.71  2.43               15.6      127.0           2.80
 1      13.20        1.78  2.14               11.2      100.0           2.65
 2      13.16        2.36  2.67               18.6      101.0           2.80
 3      14.37        1.95  2.50               16.8      113.0           3.85
 4      13.24        2.59  2.87               21.0      118.0           2.80
 ..       ...         ...   ...                ...        ...            ...
 173    13.71        5.65  2.45               20.5       95.0           1.68
 174    13.40        3.91  2.48               23.0      102.0           1.80
 175    13.27        4.28  2.26               20.0      120.0           1.59
 176    13.17        2.59  2.37               20.0      120.0           1.65
 177    14.13        4.10  2.74               24.5       96.0           2.05

      flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
 0          3.06                  0.28             2.29             5.64  1.04
 1          2.76                  0.26             1.28             4.38  1.05
 2          3.24                  0.30             2.81             5.68  1.03
 3          3.49                  0.24             2.18             7.80  0.86
 4          2.69                  0.39             1.82             4.32  1.04
 ..          ...                   ...              ...              ...   ...
 173        0.61                  0.52             1.06             7.70  0.64
 174        0.75                  0.43             1.41             7.30  0.70
 175        0.69                  0.43             1.35            10.20  0.59
 176        0.68                  0.53             1.46             9.30  0.60
 177        0.76                  0.56             1.35             9.20  0.61

      od280/od315_of_diluted_wines  proline  target
 0                            3.92   1065.0       0
 1                            3.40   1050.0       0
 2                            3.17   1185.0       0
 3                            3.45   1480.0       0
 4                            2.93    735.0       0
 ..                            ...      ...     ...
 173                          1.74    740.0       2
 174                          1.56    750.0       2
 175                          1.56    835.0       2
 176                          1.62    840.0       2
 177                          1.60    560.0       2

 [178 rows x 14 columns],
 'target': 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 173    2
 174    2
 175    2
 176    2
 177    2
 Name: target, Length: 178, dtype: int64,
 'target_names': array(['class_0', 'class_1', 'class_2'], dtype='<U7')}

In [61]:
#How many samples and features are there?

# YOUR CODE HERE
print('number of samples:', df.shape[0], 'number of features:', df.shape[1]-1)

number of samples: 178 number of features: 13

In [62]:
# Quiz Q1
# How many instances are there for each class? 

# YOUR CODE HERE
df['y'].value_counts()

1    71
0    59
2    48
Name: y, dtype: int64

In [66]:
# Calculate the means, medians, and standard deviations of each feature
# YOUR CODE HERE
df.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,y
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

In [75]:
# Plot a boxplot of each feature (NOT THE LABEL!!) (all in one plot -- you can do this with a single line of code).
# Quiz Q2: Is there any feature that is in a clearly different scale than the others?

# YOUR CODE HERE
sns.boxplot(x = data['frame'], y = df['y'], data = df)

ValueError: ignored

In [77]:
data[data]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [ ]:
# Let's look at the distributions of values of our features. Draw a histogram for each of the features

# YOUR CODE HERE

Let's do some multivariate analysis

In [ ]:
# Calculate the correlations between each pair of variables

# YOUR CODE HERE

# Plot a heatmap of the correlations between pairs of FEATURES (i.e., don't include the target!)

# YOUR CODE HERE

In [ ]:
# What is the highest correlation between features?

You should have noticed that some of the features are highly correlated. 

For this reason, we can run into trouble when trying to train a classifier due to multicolinearity.

Let's do PCA on this dataset to remove these correlations

In [ ]:
# Let's do PCA:
# HINT: I suggest you attempt Q5 of the quiz and then use the function you developed
#       in this and some of the following cells.

# 1. Standardise your data using a StandardScaler. Make sure you're not scaling the 'y'!

# YOUR CODE HERE

# 2. Do PCA with 2 components. How much variance is retained from the original dataset?

# YOUR CODE HERE

In [ ]:
# Plot your two components, using the label from the data to colour the points

# YOUR CODE HERE

In [ ]:
# How many components do you need to keep at least 85% of the variance in the dataset? (Q6)

# YOUR CODE HERE

In [ ]:
# How much variance is retained if we do PCA with 3 components? (Q7)

# YOUR CODE HERE

## Clustering

Let's see how many clusters does K-Means find.

In [ ]:
# Use the elbow method to select the number of clusters in your data using 3 PCs.

# YOUR CODE HERE

In [ ]:
# Now use the silhouette score to choose between the two candidate k values from the previous cell

# YOUR CODE HERE

In [ ]:
# Visualise the first two pcs (using a scatterplot) using the labels from KMeans with your chosen value of k

# YOUR CODE HERE

Now we can try to understand our clusters.

In [ ]:
# In the original (before PCA and before standardisation) dataframe, add a column called 'cluster' that contains
# the cluster assignment from above

# YOUR CODE HERE

In [ ]:
# Do a boxplot of each feature, separating between clusters

# YOUR CODE HERE

Write your observations here.
For example: is there a clear difference between the clusters in terms of alcohol content? What about flavanoids?

In [ ]:
# Feel free to keep playing with the data here!